### ISSUE TITLE
Installing Leland for Dorico 3.5 (Mac)

### ISSUE THREAD

**Issue by RonWoodley212** [MuseScoreFonts/Leland#11]
Can you please clarify this installation issue for use with Dorico (Mac)? (Apologies in advance for being a GitHub novice, and musician rather than techie!) 

Your advice is:
To use the font in Dorico (1.0.20 and later), the metadata.json file needs to be copied to the following location:
Mac: /Library/Application Support/SMuFL/Fonts/leland/leland.json

When I try to download <metadata.json> it downloads as an html file. If I put this in a folder created as /Library/Application Support/SMuFL/Fonts/leland/leland.json , Dorico refuses to load, as it tells me that metadata.json is in the incorrect format. Do I need to find a way to download it as other than html, or rename it, or something else, please?

**Comment by oktophonie** [comment]
The best way to get the files is to install git in some form (could be GitHub desktop) and clone the whole repo - there are various guides online for how to get started with all that stuff if you want to go down that route.

If you just want to download the metadata file, then from https://github.com/MuseScoreFonts/Leland/blob/main/metadata.json hit the 'Raw' button, and then save that.

We should put up a package soon so you can just download the whole thing as a zip file; sorry that it's a bit inconvenient, for now!

**Comment by RonWoodley212** [comment]
Thanks for this. I've tried various things again to make the folder/file structure for Leland in my SMuFL folder look the same as for the other SMuFL fonts there, but nothing works, and Dorico still fails to boot, with an 'invalid file format' error message pointing to the .json file. It's still not clear to me whether the metadata.json needs to be renamed as leland.json, and placed within a new leland folder, to make it analogous to the other .json files (which all have leading upper case names, but I don't know if this matters). I've tried both names, to no avail. I have installed the Leland.otf and LelandText.otf files, but although they show up in font menus in other apps (such as Word), they are not actually functioning properly either, so there seems to be some basic incompatibility.  I don't think it's worth my while cloning the whole repo, since I still wouldn't have a clear idea what to do with it, to make it install properly. So I guess I'm going to have to leave it for now, and clear all the Leland stuff out -- otherwise I can't use Dorico at all. It's a shame, because I like the look of Leland, from what I've seen, but it's clearly not quite ready to be installed and trialled properly in systems such as mine (and I guess many others). Thanks again, though, for the development -- it looks really promising.

**Comment by Tantacrul** [comment]
Hi Ron,

I'm also running Dorico on a Mac and I'm not having the same issue. We'll
need more time to get to the bottom of this. One question: are you able to
install both Leland and Leland Text on your Mac?

Thanks!
Martin

**Comment by RonWoodley212** [comment]
Thanks, Martin -- that's useful that you are working with a similar set-up! Yes, I mentioned in my previous message that the two fonts are installed OK, and they show up correctly in FontBook. I can't get them to do much e.g. in Word, even though they appear in the font menu, but that may just be a corollary of the non-standard encoding for text purposes. But even though they are installed, Leland doesn't show up in Dorico in the Engrave --> Music Fonts menu, unlike the other three SMuFL fonts that I have (Bravura, November 2, and Petaluma). So I'm guessing that the problem lies with the metadata file in the Library SMuFL folder. Can you describe exactly what named Leland file you have in what folder structure on your system, please, so that I can try to reproduce this?

Best,

Ron

**Comment by Tantacrul** [comment]
I renamed the json 'Leland' and I put it in a folder called 'Leland' in the
directory stated in the instructions. *Your HD / Library / Application
Support / SMuFL / Fonts*

Make sure to restart your computer and Dorico too.

Apart from that, I'm not sure what else you can do.

Thanks!
Martin

**Comment by RonWoodley212** [comment]
Yes, that's exactly what I did, with the restart as well! However, I'll try it again now, with renewed confidence...!

Thanks again,

Ron

**Comment by RonWoodley212** [comment]
Nope, the same error message as before, after restart (see attached image, if it uploads OK). I guess I'll just have to give up for now...
![Screenshot 2021-01-26 at 21 06 24](https://user-images.githubusercontent.com/78021871/105905815-d1310900-601a-11eb-9304-add190696c39.png)

**Comment by snakebyte69** [comment]
<img width="621" alt="Screen Shot 2021-02-14 at 6 00 44 pm" src="https://user-images.githubusercontent.com/39090848/107870698-b8679500-6eee-11eb-8fde-7143cf5e60b2.png">

**Comment by RonWoodley212** [comment]
Thanks, snakebyte69. I have installed Leland.otf and LelandText.otf fine. The problem at my end has always been (as far as I can tell) with the metadata.json file. I have followed the installation instructions for this file to the letter, but I still get the error message that I posted before (screenshot above, 26 January) when I launch Dorico. I am wondering if something odd happens when I download the metadata file. It downloads as metadata.json.html rather than just metadata.json. I change the filename to Leland.json, as per instructions, my OS asks for confirmation of the change, but then the error occurs on launch of Dorico. Is there some kind of misinterpretation of .json and .html file extensions going on here?

**Comment by oktophonie** [comment]
As I mentioned before, it sounds like you're trying to save the metadata file directly from the GitHub page, and so you're getting precisely that - the html page on which it's displayed, not just the contents of the file itself.

The easiest thing to do now is download the latest release as a zip file (https://github.com/MuseScoreFonts/Leland/releases/) and use the metadata.json file contained therein, which will definitely be in the correct format. Of course, if you still have problems with _that_, do let me know.

**Comment by RonWoodley212** [comment]
Finally, this works -- thanks very much, Simon! I had previously tried the way you suggested, to download the .json file, but nothing else seemed to work. Now I have it, though!

**Comment by oktophonie** [comment]
A pleasure! Will track the issue mentioned here by @snakebyte69 via his other reports (thanks for those).
