### ISSUE TITLE
MacOS FontBook shows error when validating font files

### ISSUE THREAD

**Issue by snakebyte69** [MuseScoreFonts/Leland#13]
1 serious error was found. Do not use this font file.

I'm sure it's some annoying Apple requirement that's an easy fix.

<img width="621" alt="Screen Shot 2021-02-14 at 6 00 44 pm" src="https://user-images.githubusercontent.com/39090848/107870712-e3ea7f80-6eee-11eb-89f8-fb91da576473.png">

**Comment by oktophonie** [comment]
It would be helpful of Font Book to give some information about what the specific error is :)
Unfortunately we haven't been able to reproduce this problem locally, yet.

**Comment by snakebyte69** [comment]
I've tested again with the new version v0.52.
