### ISSUE TITLE
Missing restQuarterZ

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#14]
It would be nice if you could add a `restQuarterZ` glyph.

**Comment by Tantacrul** [comment]
![image](https://user-images.githubusercontent.com/21022311/124336377-bba9a780-db95-11eb-98cf-38b2c72bf7e2.png)

Added. Will be available in the next release.

**Comment by oktophonie** [comment]
Added in 56fb8c167f9194f8b44b59a93544fa9bfcc57579
