### ISSUE TITLE
Wrong direction for arpeggio arrow down

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#17]
The SMuFL specification changed on code point U+EAAE:
https://www.smufl.org/version/latest/range/multiSegmentLines/
https://w3c.github.io/smufl/latest/tables/multi-segment-lines.html

see fkretlow/sebastian#4
This will probably have to be touched in MuseScore too.

**Comment by Jojo-Schmitz** [comment]
Is that a problem in MuseScore? I do remember to have changed the code to adjust for this change

**Comment by Jojo-Schmitz** [comment]
See https://github.com/musescore/musescore/commit/70222c9a

**Comment by rettinghaus** [comment]
@Jojo-Schmitz I see (although this is not really a fix 😉)

**Comment by Jojo-Schmitz** [comment]
It was needed for all fonts, Bravura included...

**Comment by rettinghaus** [comment]
Fixed in f01986dc2371a1ae11f74e169810c5c5fe00f517

**Comment by Jojo-Schmitz** [comment]
Hmm, that fix isn't mentioned in https://github.com/MuseScoreFonts/Leland/commit/f01986dc2371a1ae11f74e169810c5c5fe00f517#diff-15adbc9abf9a964c53aa51a6344085579f4a53dcde8f095d9d4b63f5bfaa2faa
