### ISSUE TITLE
Missing points at extrema in release 0.6.1

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#18]
Release claims it has 

> Added missing points at extrema throughout

Still the following have missing points:

- E054
- E07A
- E083
- E087
- E240
- E285
- E517
- E518
- E519
- E51E
- E562
- E563
- E650
- E651

**Comment by Tantacrul** [comment]
Are you getting this from a FontForge report?

**Comment by rettinghaus** [comment]
Yes, it is indeed FontForge.

**Comment by oktophonie** [comment]
These should now be fixed in https://github.com/MuseScoreFonts/Leland/releases/tag/v0.72

**Comment by Jojo-Schmitz** [comment]
So this issue can get closed I guess

**Comment by rettinghaus** [comment]
Actually Fontforge still complains about E650 and E651 from this list.

**Comment by Tantacrul** [comment]
Just cleaned up both of those, which, oddly neither my version of FontForge or FontLab complained about. However, I could see that they symbols could do with a little optimisation, so nice catch.

**Comment by Jojo-Schmitz** [comment]
So for 0.73?

**Comment by oktophonie** [comment]
Fixed in [0.73](https://github.com/MuseScoreFonts/Leland/releases/tag/v0.73)
