### ISSUE TITLE
Refine double whole noteheads

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#19]
Currently the standard double whole note only has one vertical line on each side instead of two. According to SMuFL specs this should rather be an alternate glyph: https://www.w3.org/2019/03/smufl13/tables/noteheads.html#recommended-stylistic-alternates

The breve head (noteheadDoubleWholeSquare) looks disproportionately wide. It is too thin compared to the normal whole notehead. And in most classic prints I looked up the vertical lines spread almost two staff spaces. Here are some examples:

![image](https://user-images.githubusercontent.com/7693447/137152760-a6841487-6d16-437c-8a07-ff15626bd41d.png)
![image](https://user-images.githubusercontent.com/7693447/137152785-4d3bf362-056c-42fc-983f-c18edb2b328f.png)
![image](https://user-images.githubusercontent.com/7693447/137152896-aba6ba65-21f3-46b4-9c80-04171e4695a6.png)

**Comment by rettinghaus** [comment]
Thanks! To me it looks too wide. I would keep it within the boundaries of the other double whole glyph. But mainly the horizontal lines are too thin compared to their width.

**Comment by oktophonie** [comment]
The double-vertical-line note has been added in https://github.com/MuseScoreFonts/Leland/releases/tag/v0.72 and the old version is now a stylistic alternate for it, as per SMuFL.

The design of the square double-whole note is actually as intended, so has not changed for now.

**Comment by Jojo-Schmitz** [comment]
So this issue can get closed I guess

**Comment by rettinghaus** [comment]
Yes.
