### ISSUE TITLE
Flat flags

### ISSUE THREAD

**Issue by gilbertohasnofb** [MuseScoreFonts/Leland#2]
Thank you so much for this new font, this is such a great effort. I am interested in using Leland with LilyPond, since it is SMuFL compliant. I just wanted to ask whether Leland support different types of flags (since, as far as I know, MuseScore itself doesn't). LilyPond supports multiple types of flags for a same font, e.g.:

![image](https://user-images.githubusercontent.com/5700795/104762779-d2318300-575c-11eb-9a1b-c6514b428db0.png)

The second style above, flat flags, is particularly interesting for me as it is quite commonly used in the contemporary music repertoire I work with. The angled straight flags are also fairly common in the modernist repertoire of the mid-20th century (e.g. most Boulez music engraved by Universal Editions). Does Leland support those by any chance?

**Comment by oktophonie** [comment]
Not yet, but they will! (they are currently in progress)

**Comment by gilbertohasnofb** [comment]
Thanks for the super quick reply as well as for the information. Good luck with the development!

**Comment by DWW256** [comment]
Does Leland work with LilyPond at all?  I would love to use it but couldn't figure out how… :(

**Comment by oktophonie** [comment]
I don't believe that LilyPond supports the SMuFL standard at this time, so Leland will not work properly. It seems to get discussed from time to time, so with any luck it will become possible at some point.

**Comment by gilbertohasnofb** [comment]
Yes, LilyPond can make use of SMuFL fonts. Unfortunately this is not supported out of the box and requires a snippet from the OpenLilyLib rep: https://github.com/openlilylib/snippets/tree/master/custom-music-fonts/smufl

**Comment by oktophonie** [comment]
Thanks for the pointer!

**Comment by gilbertohasnofb** [comment]
No problems! Here's an example of it in practice; Emmentaler is LilyPond's default font, Bravura is the font designed by Daniel Spreadbury for Dorico:

![image](https://user-images.githubusercontent.com/5700795/112970193-d824e680-9145-11eb-90fe-a7fc212c781c.png)

**Comment by Jojo-Schmitz** [comment]
Really 'Emmentaller' with a double l?

**Comment by gilbertohasnofb** [comment]
@Jojo-Schmitz No, it's a typo. But just FYI, there are kinder ways of pointing that out. I'm not a native speaker.

**Comment by Jojo-Schmitz** [comment]
I'm not a navive speaker either and didn't intend to be unkind, just curious. While I know for sure that the cheese is called Emmentaler, it might have been possible that font is spelled Emmentaller (and MuseScore is spelling it wrong ever since). Glad that this is not the case ;-)

**Comment by gilbertohasnofb** [comment]
No problems, @Jojo-Schmitz, I think I read your message in the wrong tone.

**Comment by Tantacrul** [comment]
Flat flags are now in, although we have not enabled them in MuseScore (yet).

**Comment by oktophonie** [comment]
Technically _straight_ flags are in, but _flat_ ones are a different thing.

These would be easy to add as another stylistic set, but they aren't explicitly defined or referenced in SMuFL (nor does Bravura itself contain them as far as I can see); what I suspect LilyPond does is draw them as primitives akin to short beam fragments.

**Comment by Tantacrul** [comment]
Let's break the mould!

**Comment by DWW256** [comment]
Tried the OpenLilyLib snippet with Leland and it definitely did not work.  I think there are a lot of quirks that are basically manually optimized for Bravura, but I am not certain.  Probably it would be easiest just to spin the SMuFL font off into a separate LilyPond-format font like Profondo was for Bravura, but it almost might as well be a separate project at that point.  A separate GitHub issue at least :)

**Comment by oktophonie** [comment]
Straight flags were added in v0.6; 'flat' flags aren't planned to be added to the font itself but could be drawn by the software as primitives. (Support for these is therefore software-dependent.)

**Comment by gilbertohasnofb** [comment]
@oktophonie @Tantacrul Thank you for implementing straight flags. Concerning the flat flags, would you suggest I open a ticket in the main MuseScore repository since those need to be drawn as primitives rather than on the font side?

**Comment by oktophonie** [comment]
By all means make a feature request, but I can say that this certainly wouldn't be implemented for MuseScore 4.0 and (if I'm being brutally honest) is unlikely to be considered a high-priority feature in the near future. Unless loads of people start clamouring for it of course! (and there's nothing to say that an open-source contributor won't come along who is desperately keen to implement it)
