### ISSUE TITLE
Complete bar repeats range

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#20]
It would be good to have the complete [Bar repeats range](https://w3c.github.io/smufl/latest/tables/bar-repeats.html) available, for repeat-beat abbreviations:

![image](https://user-images.githubusercontent.com/7693447/143035245-666ef249-0cbe-4a0e-87d2-50f84e247d13.png)
(Behind Bars, p. 230)

**Comment by Jojo-Schmitz** [comment]
Those (something like `repeat[123]Beats`) are not in SMuFL, opposed to the `repeat[124]Bars`, but what keeps you from using 1, 2 or 3 `repeatBarSlash`, which do exist and do work.

**Comment by oktophonie** [comment]
Leland does not yet have the isolated slash (E504), nor the dots as separate components (E503/E505), but these will be added in v0.74 this week.

**Comment by Jojo-Schmitz** [comment]
Ah, I see. Only MuseScore falls back to Bravura there.

**Comment by oktophonie** [comment]
Added E503-E505 in [v0.74](https://github.com/MuseScoreFonts/Leland/releases/tag/v0.74)
