### ISSUE TITLE
noteheadNull has no width

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#21]
The glyph U+E0A5 noteheadNull is expected to have a width that matches those of the other noteheads, but in Leland currently it has no width at all.

**Comment by Jojo-Schmitz** [comment]
Seems it is in good company with Bravura there, see https://github.com/steinbergmedia/bravura/issues/63

**Comment by rettinghaus** [comment]
@Jojo-Schmitz no, that's a different one. The glyph in Bravura has a width, the information is just missing in the metadata file.

**Comment by Jojo-Schmitz** [comment]
Ah, I see, somewhat related but different

**Comment by oktophonie** [comment]
Corrected in [v0.75](https://github.com/MuseScoreFonts/Leland/releases/tag/v0.75).
