### ISSUE TITLE
Tremolo glyphs should be centered

### ISSUE THREAD

**Issue by rettinghaus** [MuseScoreFonts/Leland#23]
The slash glyphs in the tremolo range (U+E220 – U+E229) are supposed to be centered on the glyph origin, but instead are left-aligned to the origin.

See: https://w3c.github.io/smufl/latest/tables/tremolos.html

**Comment by Tantacrul** [comment]
Hmmm. So it is. 

Incidentally, have you noticed this causing displacement of tremolos on any application?

**Comment by rettinghaus** [comment]
Yes, in Verovio:
![btrem](https://user-images.githubusercontent.com/7693447/155735016-21a75b01-2101-4097-a415-3e9e4a9a5ec1.png)

**Comment by Tantacrul** [comment]
OK. Thanks a lot!

**Comment by Tantacrul** [comment]
@oktophonie, I've fixed these. Can you confirm they're still working in the regular places and then merge, when it takes your fancy?

**Comment by oktophonie** [comment]
Fixed in [v0.76](https://github.com/MuseScoreFonts/Leland/releases/tag/v0.76)
