### ISSUE TITLE
Undefined `sustainedBuzzRoll` glyph in glyphBBoxes of SMuFL metadata

### ISSUE THREAD

**Issue by dbuenzli** [MuseScoreFonts/Leland#24]
The `glyphBBoxes` field of the SMuFL metadata has a bounding box for a glyph named [`sustainedBuzzRoll`](https://github.com/MuseScoreFonts/Leland/blob/3c5cea82b3bbd92e833e0e6a7037129e821243d8/leland_metadata.json#L4078-L4086) which doesn't seem to be described anywhere.

I can't find this glyph name in the [SMuFL list of glyphs](https://github.com/w3c/smufl/blob/gh-pages/metadata/glyphnames.json). 

Did you maybe forget to describe it in the [`optionalGlyph`](https://w3c.github.io/smufl/latest/specification/optionalglyphs.html) field of the metadata ?

**Comment by oktophonie** [comment]
Just so! I will add the `optionalGlyph` info.

**Comment by oktophonie** [comment]
Fixed in [v0.76](https://github.com/MuseScoreFonts/Leland/releases/tag/v0.76)
