### ISSUE TITLE
Switch version scheme to Semantic Versioning

### ISSUE THREAD

**Issue by throwaway1037** [MuseScoreFonts/Leland#26]
https://SemVer.org

**Comment by oktophonie** [comment]
Font metadata only allows two parts to the version number, not the three required for semantic versioning.

From 1.0, which will coincide with the release of MuseScore 4.0, we will likely switch to _M.mpp_ (M = major, m = minor, p = patch), as described [here](https://silnrsi.github.io/FDBP/en-US/Versioning.html).
(So far it's effectively been _0.mp_, but rather informal.)

**Comment by throwaway1037** [comment]
Would it be faesible to update the metadata format to use a three-part version number as prescribed by SemVer?

**Comment by oktophonie** [comment]
Not really. It's to do with the fields available in the OpenType format; see the discussion [here](https://groups.google.com/g/googlefonts-discuss/c/w6-i0Opikbc/m/nlFPEibsCQ8J).
