### ISSUE TITLE
Clarify "other application" vs other music notation software. README.md

### ISSUE THREAD

**Issue by jeetee** [MuseScoreFonts/Leland#7]
At this point an unsuspecting user might assume that the font will work in Sibelius/Finale if they just install the otf. It might be worth mentioning that the font is not yet compatible with these software packets.

**Comment by jeetee** [comment]
This request/confusion arose in one of the YouTube comments on the font video.

**Comment by oktophonie** [comment]
Good point! Added with https://github.com/MuseScoreFonts/Leland/commit/b40fe303688e359e177717f685f49bbbe7e27eec
