### ISSUE TITLE
Breve rest

### ISSUE THREAD

**Issue by craigsapp** [MuseScoreFonts/Leland#9]
The breve rest in the Leland font is very wide:

<img width="416" alt="Screen Shot 2021-01-23 at 7 05 48 AM" src="https://user-images.githubusercontent.com/3487289/105612239-a4a59480-5d6f-11eb-9991-914ebd90a72c.png">

Compare to Bravura:

<img width="415" alt="Screen Shot 2021-01-23 at 7 06 30 AM" src="https://user-images.githubusercontent.com/3487289/105612248-acfdcf80-5d6f-11eb-9b42-558eb4e990c5.png">

See: https://www.smufl.org/version/latest/range/rests
Also the Wikipedia entry about rests: https://en.wikipedia.org/wiki/Rest_(music)
where such a wide rest is not presented or discussed.

The source of the problem is that this is SCORE's breve rest, but if this is not a mistake in SCORE, then it is a very minority style for breve rests that I have not seen elsewhere.

Breve rests are rare in modern scores, but more common in older scores.  Here is an example use in a full score:

Leland font version:
https://verovio.humdrum.org/?file=jrp:Jos2707&k=ey&font=leland

Bravura font version:
https://verovio.humdrum.org/?file=jrp:Jos2707&k=ey&font=bravura

The rest is too prominent compared to the notes.  It also roughly has the same shape as a notehead which can decrease readability.  In mensural music (which the above examples are a minimimally adapted from), that shape is actually a note: In white mensural notation (used predominantly from 1450-1600) it is a colored breve (usually meaning a triplet breve), and in black notation (used predominantly from 1300-1450) it is a normal breve note.  So the Leland font cannot be used for mensural music unless this rest is fixed to the more standard thinner shape.

See https://www.smufl.org/version/latest/range/medievalAndRenaissanceIndividualNotes
And in particular U+E952 "Black mensural brevis"

**Comment by oktophonie** [comment]
Thanks for this!
The breve rest has been narrowed in https://github.com/MuseScoreFonts/Leland/commit/9bfb577558364c186991c27d9d06de549a6d1092

**Comment by rettinghaus** [comment]
Looks great with version 0.51
![rest-013_001](https://user-images.githubusercontent.com/7693447/105960361-6533bc80-607d-11eb-8aed-4355160a97d4.png)
